http:
 listener:
   host: "localhost"
   port: "8081"

db:
 sf:
  name: "SBMQKDP-TT42813"
  warehouse: "COMPUTE_WH"
  schema: "TSET"
  database: "MYDATABASE"
  user: "SINGSING"
  password: "Singsing@123456789"
  role:  "ACCOUNTADMIN"

email:
  config:
   host: "smtp.gmail.com"
   port: "587"
   user: "narsingbeesetti06@gmail.com"
   password: "kejo yanz wjpo vnum"
   key: "mail.smtp.starttls.enable"
   value: "true"
         
    